Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Vendas.Models;
using Vendas.Repositorios;

namespace Vendas.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepositorio _clienteRepositorio;
        public ClienteController(IClienteRepositorio clienteRepositorio)
        {
            _clienteRepositorio = clienteRepositorio;
        }

        public IActionResult Index()
        {
            var clientes = _clienteRepositorio.GetClientes();
            return View(clientes);
        }

        public IActionResult CreateClient()
        {
            return View();
        }

        public IActionResult UpdateClient(int id)
        {
            var cliente = _clienteRepositorio.GetClienteById(id);
            return View(cliente);
        }

        public IActionResult DeleteClient(int id)
        {
            var cliente = _clienteRepositorio.GetClienteById(id);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult CreateClient(Cliente cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clienteRepositorio.Adicionar(cliente);
                    TempData["MessageSuccess"] = "Cliente Cadastrado Com Sucesso!";
                    return RedirectToAction("Index");
                }
                return View(cliente);
            }
            catch (Exception ex)
            {
                TempData["MessageError"] = $"Ops! Não Foi Possível Cadastrar Esse Cliente! Detalhe: {ex.Message}";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult UpdateClient(Cliente cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clienteRepositorio.Update(cliente);
                    TempData["MessageSuccess"] = "Cliente Alterado Com Sucesso!";
                    return RedirectToAction("Index");
                }
                return View(cliente);
            }
            catch (Exception ex)
            {
                TempData["MessageError"] = $"Ops! Não Foi Possível Alterar Esse Cliente! Detalhe: {ex.Message}";
                return RedirectToAction("Index");
            }

        }

        public IActionResult Delete(int id)
        {
            try
            {
                _clienteRepositorio.Delete(id);
                TempData["MessageSuccess"] = "Cliente Deletado Com Sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["MessageSuccess"] = $"Ops! Não Foi Possível Deletar Esse Cliente! Detalhe: {ex.Message}";
                return RedirectToAction("Index");
            }

        }
    }
}

Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Vendas.Models;
using Vendas.Repositorios;

namespace Vendas.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepositorio _produtoRepositorio;
        public ProdutoController(IProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            var produtos = _produtoRepositorio.GetProdutos();
            return View(produtos);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }

        public IActionResult UpdateProduct(int id)
        {
            var produto = _produtoRepositorio.GetProdutoById(id);
            return View(produto);
        }

        public IActionResult DeleteProduct(int id)
        {
            var produto = _produtoRepositorio.GetProdutoById(id);
            return View(produto);
        }

        [HttpPost]
        public IActionResult CreateProduct(Produto produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Adicionar(produto);
                    TempData["MessageSuccess"] = "Produto Cadastrado Com Sucesso!";
                    return RedirectToAction("Index");
                }
                return View(produto);
            }
            catch (Exception ex)
            {
                TempData["MessageError"] = $"Ops! Não Foi Possível Cadastrar Esse Produto! Detalhe: {ex.Message}";
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult UpdateProduct(Produto produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Update(produto);
                    TempData["MessageSuccess"] = "Produto Alterado Com Sucesso!";
                    return RedirectToAction("Index");
                }
                return View(produto);
            }
            catch (Exception ex) 
            {
                TempData["MessageError"] = $"Ops! Não Foi Possível Alterar Esse Produto! Detalhe: {ex.Message}";
                return RedirectToAction("Index");
            }
            
        }

        public IActionResult Delete(int id)
        {
            try
            {
                _produtoRepositorio.Delete(id);
                TempData["MessageSuccess"] = "Produto Deletado Com Sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["MessageSuccess"] = $"Ops! Não Foi Possível Deletar Esse Produto! Detalhe: {ex.Message}";
                return RedirectToAction("Index");
            }
            
        }
    }
}

Controllers/VendaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Vendas.Models;
using Vendas.Repositorios;

namespace Vendas.Controllers
{
    public class VendaController : Controller
    {
        private readonly IVendaRepositorio _vendaRepositorio;
        private readonly IProdutoRepositorio _produtoRepositorio;
        private readonly IClienteRepositorio _clienteRepositorio;

        public VendaController(IVendaRepositorio vendaRepositorio, IProdutoRepositorio produtoRepositorio, IClienteRepositorio clienteRepositorio)
        {
            _vendaRepositorio = vendaRepositorio;
            _produtoRepositorio = produtoRepositorio;
            _clienteRepositorio = clienteRepositorio;
        }

        public IActionResult Index()
        {
            var venda = _vendaRepositorio.GetVendas();
            return View(venda);
        }
        public IActionResult CreateVenda()
        {
            var produtos = _produtoRepositorio.GetProdutos();
            var produtosVenda = new List<Venda>();
            foreach (var produto in produtos)
            {
                var venda = new Venda();
                venda.Produto = produto;
                produtosVenda.Add(venda);
            }            

            var clientes = _clienteRepositorio.GetClientes();
            ViewBag.Clientes = clientes;

            return View(produtosVenda);
        }
        public void AdicionarCarrinho(int id)
        {
            var produto = _produtoRepositorio.GetProdutos();
            ViewBag.ProdutosAdicionados = produto;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro de Vendas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vendas.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" type="text/css" rel="stylesheet" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro de Vendas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venda" asp-action="Index">Vendas</a>
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cadastro de Vendas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>